version: '3'

#5.2.2-php7.2-fpm

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
       - "8085:80"
       - "4436:443"
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - wordpress:/var/www/html
    networks: 
        - wordpress_network

  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
        - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: akuganteng
        MYSQL_ROOT_PASSWORD: akuganteng90
    ports:
        - '3306:3306'
    networks: 
        - wordpress_network

  wordpress:
    image: wordpress:5.2.2-php7.2-fpm
    container_name: wordpress
    restart: always
    ports:
        - '9000:9000'
    environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: akuganteng
    volumes:
        - wordpress:/var/www/html
    networks: 
        - wordpress_network
    depends_on: 
        - mysql
        - nginx
    # links:
    #   - "mysql"

networks:
    wordpress_network:
        driver: bridge