version: '3'


volumes:
  wordpress:
    driver: local
  mysql:
    driver: local

services:
  mysql:
    image: mysql:5.6
    volumes:
        - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    deploy:
        mode: replicated
        replicas: 2
        restart_policy:
          condition: on-failure
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: akuganteng
        MYSQL_ROOT_PASSWORD: akuganteng90
    ports:
        - '3306:3306'
    networks: 
        - wordpress_overlay

  wordpress:
      image: wordpress:latest
      volumes:
        - wordpress:/var/www/html
      ports:
        - "8195:80"
      depends_on:
        - mysql
      deploy:
        mode: replicated
        replicas: 5
        restart_policy:
          condition: on-failure
      environment:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_PASSWORD: akuganteng
      networks:
        - wordpress_overlay

networks:
    wordpress_overlay:
        # driver: overlay
        external: true
